#!/bin/bash

version="2.48"
depends=("make" "gcc" "glibc" "tar" "xz-utils" "ninja" "meson" "xtrans" "libX11" "libXext" "libFS" "libICE" "libSM" "libXScrnSaver" "libXt" "libXmu" "libXpm" "libXaw" "libXfixes" "libXcomposite" "libXrender" "libXcursor" "libXdamage" "libfontenc" "libXfont2" "libXft" "libXi" "libXinerama" "libXrandr" "libXres" "libXtst" "libXv" "libXvMC" "libXxf86dga" "libXxf86vm" "libpciaccess" "libxkbfile" "libxshmfence" "libXpresent")

install() {
    rm -f xkeyboard-config-$version.tar.xz
    wget https://www.x.org/pub/individual/data/xkeyboard-config/xkeyboard-config-$version.tar.xz
    rm -rf xkeyboard-config/
    mkdir -p xkeyboard-config/
    tar -xf xkeyboard-config-$version.tar.xz -C xkeyboard-config --strip-components=1
    cd xkeyboard-config/
    mkdir build
    cd build

    meson setup --prefix=/usr --buildtype=release ..
    ninja
    ninja install
}

remove() {
    cd xkeyboard-config
    ninja -C build uninstall
}
