#!/bin/bash

version="6.8.2"
depends=("make" "gcc" "glibc" "tar" "libcrypt" "linux-pam")

install() {
    rm -f v$version.tar.gz
    wget https://github.com/Duncaen/OpenDoas/archive/refs/tags/v$version.tar.gz
    rm -rf doas/
    mkdir -p doas/
    tar -xf v$version.tar.gz -C doas --strip-components=1
    cd doas/
    ./configure --prefix=/usr --with-timestamp
    make
    make install
	cat << 'EOF' > /etc/pam.d/doas
auth     required    pam_unix.so
account  required    pam_unix.so
session  required    pam_unix.so
EOF
}

remove() {
    cd doas/
    make uninstall
}
