#!/bin/bash

version="0.19"
depends=("make" "gcc" "glibc" "tar" "fontconfig" "libxcb" "xz-utils" "ninja" "meson")
lib="libpciaccess"

install() {
    rm -f $lib-$version.tar.xz
    wget https://www.x.org/pub/individual/lib/$lib-$version.tar.xz
    rm -rf $lib/
    mkdir -p $lib/
    tar -xf $lib-$version.tar.xz -C $lib --strip-components=1
    cd $lib/
    meson setup --prefix=$XORG_PREFIX --buildtype=release build
    ninja -C build
    ninja -C build install
}

remove() {
    cd $lib/
    ninja -C build uninstall
}
